export const demoImageUrl = "https://www.bing.com/th?id=OVFT.mpzuVZnv8dwIMRfQGPbOPC&pid=News"
export const messagesRouteRegExp = /\/messages\/?/
export const editPostRouteRegExp = /\/(explore\/)?(suggests|posts)\/editPost\/.*/
export const tradingviewSupportHost = "https://www.tradingview.com"
export const nobitexMarketChart = "https://nobitex.ir/nobitex-cdn/charts/"
export const appwriteEndpoint = "https://cloud.appwrite.io/v1"
export const appwriteProjectId = import.meta.env.VITE_APPWRITE_PROJECT_ID
export const appwritePostsBucketId = import.meta.env.VITE_APPWRITE_POSTS_BUCKET_ID
export const appwriteSignalsBucketId = import.meta.env.VITE_APPWRITE_SIGNALS_BUCKET_ID
export const appwriteMessagesBucketId = import.meta.env.VITE_APPWRITE_MESSAGES_BUCKET_ID
export const mongoDBURI = import.meta.env.VITE_MONGO_URI
